name: benchmark
publish_to: none
version: 1.3.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.12.0
  astar_dart:
    path: ../
  benchmark_harness: ^2.3.1
  a_star_algorithm: ^0.4.1
  a_star: ^3.0.1
  sector: ^0.4.0+1

dev_dependencies:
  test: any
