name: astar_dart
description: "A pathfinding implementation in Dart. Efficiently finds shortest paths on grids, supporting barriers and weights. Manhattan, Euclidean, Hex"
version: 2.2.1
license: MIT
homepage: https://github.com/s1r1m1r1/astar_dart

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  collection: ^1.18.0
  array2d: ^1.0.0
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.4.14
  build_version: ^2.1.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

topics:
  - astar
  - pathfinding
  - manhattan
  - euclidean 
  - hex 
