name: astar_dart
description: "a pathfinding implementation in Dart. Efficiently finds shortest paths on grids, supporting barriers and weights."
version: 1.0.1
homepage: https://github.com/Sproute777/astar_dart

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  collection: ^1.18.0
  meta: ^1.12.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

topics:
  - astar
  - path-finding
